[project]
name = "churn-prediction-mlops"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.11.1",
    "mlflow>=2.14",
    "pandas>=2.2,<3",
    "prefect>=3.8.4",
    "protobuf<5",
    "scikit-learn>=1.9.0",
    "seaborn>=0.13.2",
    "setuptools<80",
    "ucimlrepo>=0.0.7",
    "xgboost>=3.2.0",
]

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
    "ruff>=0.16.5",
]
